### ISSUE TITLE
[JS Bug][iOS]: Unable to decode response: The operation couldn't be completed

### ISSUE THREAD

**Issue by Wojciech-Florczak** [microsoft/live-share-sdk#369] opened 2023-02-09 12:52 UTC
- [x] I have reviewed the FAQ and known issues and did not find my topic

**Describe the bug**

Error happens while using `client.joinContainer(schema)`. 

```js
import { LiveEvent, LivePresence, LiveShareClient } from '@microsoft/live-share';
import { LiveCanvas } from '@microsoft/live-share-canvas';
import { LiveMediaSession } from '@microsoft/live-share-media';
import { LiveShareHost } from '@microsoft/teams-js';
import { SharedMap } from 'fluid-framework';

  const createClient = async () => {
    const host = LiveShareHost.create();
    const client = new LiveShareClient(host);
    const schema = {
      initialObjects: {
        presence: LivePresence,
        mediaSession: LiveMediaSession,
        notificationEvent: LiveEvent,
        liveCanvas: LiveCanvas,
        takeControlMap: SharedMap,
        playlistMap: SharedMap,
      },
    };
    try {
      const res = await client.joinContainer(schema);
      setResults(res.container);
    } catch (error) {
      setError(error);
    }
    return container;
  };
```

Error in this function is only returned in one case - when using iOS device.

`Unable to decode response: The operation couldn't be completed. (ExtensibilityPlatform.EPInteractiveEventProcessor.InteractiveError error 2.)`

**To Reproduce**

> Steps to reproduce the behavior:

1. Create `LiveShareClient`
2. Try to use `client.joinContainer()`
3. Try to access `container` in `iOS` and log data from `error` to screen

**Expected behavior**

I expect `LiveShare` to load properly, istead I receive this error

**Screenshots**
![obraz](https://user-images.githubusercontent.com/53352540/217806487-dcc9cd7b-d685-4794-8648-527cc9d91827.png)

**Smartphone:**

- Device: [iPhone13 mini]
- OS: [iOS16.3]
- Browser [MS Teams app]
- Version [5.2.0]

**Additional context**

I've tried different packages versions:
[`@microsoft/live-share`, `@microsoft/live-share-canvas`, `@microsoft/live-share-media`] - `1.0.0-preview.1`
`@microsoft/teams-js` - `2.0.0-experimental.1`

and 

[`@microsoft/live-share`, `@microsoft/live-share-canvas`, `@microsoft/live-share-media`] - `1.0.0-preview.4`
`@microsoft/teams-js` - `2.8.0`

**Comment by ryanbliss** [comment] 2023-02-09 19:20
Thanks for reporting this! We'll investigate and get back to you.

**Comment by ryanbliss** [comment] 2023-02-21 23:45
@Wojciech-Florczak we haven't been able to reproduce this issue. Does this happen every time on iOS?

**Comment by Wojciech-Florczak** [comment] 2023-02-27 08:55
> @Wojciech-Florczak we haven't been able to reproduce this issue. Does this happen every time on iOS?

Yes, I've tried on a few iOS devices with different os version

**Comment by ryanbliss** [comment] 2023-03-01 01:32
@wpietrak Thanks for the update. Is the iOS client updated to the latest version of Teams on the app store?

**Comment by wpietrak** [comment] 2023-03-01 07:21
@ryanbliss it was 5.3.0 version of Teams.

**Comment by ryanbliss** [comment] 2023-03-01 07:32
Thanks @wpietrak. That's the same version I'm on so it's not be that. We have our iOS engineering team looking at this now. Thank you so much for all the details, it really helps!

**Comment by ryanbliss** [comment] 2023-03-01 22:56
We are working on correlating the error code we see on the client to service telemetry, but it's taking some time since we don't have a repro.

There is an app called Charles Proxy on iOS that we use to get network traces while testing in Teams. It costs $8, but there may be free alternatives out there. If possible, it would be helpful to see those with SSL Proxying enabled. A text file with that (with any access tokens scrubbed) would be great to see. If you do, please send that to my email is ryanbliss@microsoft.com. 

I know this is a lot to ask, so if you can't do this we'll keep investigating in the meantime. Thank you!

**Comment by ryanbliss** [comment] 2023-03-03 18:45
@wpietrak were you logged into the same Teams account on iOS as you were on Android / desktop? For example, if it is an "anonymous" account on iOS, that isn't yet supported (though it will be this year). Our mobile team identified the issue that is causing this error message to not be returned in a human-readable format, which is making this specific error hard to pinpoint. But any information about what might differentiate the iOS account you joined the meeting from that is different from Android/web could help.

Thank you!

**Comment by Wojciech-Florczak** [comment] 2023-03-06 06:20
For testing we've used accounts generated in Microsoft 365 Developer Program. On web it was main account, and on iOS it was a generated one

**Comment by wpietrak** [comment] 2023-03-08 10:37
@ryanbliss is it possible that also Developer account (which is used in our case to run application in Teams) cause problems. Or were you able to generate error when using developer account?

**Comment by ryanbliss** [comment] 2023-03-20 17:15
@wpietrak sorry for the delay. I did talk to some of our developers about this a couple of weeks ago and it is possible, but I'm not sure why. There are two issues here:
1. The error you are getting isn't very helpful. An update is rolling out on iOS that will make that error more legible and help us debug better in the future. Unfortunately, these error strings made their way into our other telemetry as well. This issue is unique to iOS.
2. The actual error itself, which we have been unable to reproduce so far. The developer account is a good hint though...we'll dig in, thank you.

**Comment by ryanbliss** [comment] 2023-04-13 19:30
The error messages should be more descriptive now and issues less frequent. @wpietrak / @Wojciech-Florczak if you happen to give this another try (ensuring your iOS app is updated to the latest version), could you please let us know what the updated error message is (if any)?

**Comment by ryanbliss** [comment] 2023-05-07 22:41
Closing for now, but let me know if you are still encountering it in the newest public builds.

**Closed by ryanbliss** 2023-05-07 22:41 UTC
Labels: bug, teams client work
